version: '3'

services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data

  app:
    build: ./app
    environment:
      - APP_PORT=${APP_PORT}
      - FLASK_PORT=${FLASK_PORT}
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
    image: app
    hostname: app
    container_name: app
    restart: always
    links:
      - redis
    ports:
      - ${APP_PORT}:${FLASK_PORT}

  worker:
    build: ./worker
    environment:
      - TEMP_DIR=${TEMP_DIR}
      - REDIS_URL=${REDIS_URL}
      - YTDL_OPTS_OUTTMPL=${YTDL_OPTS_OUTTMPL}
      - YTDL_OPTS_FORMAT=${YTDL_OPTS_FORMAT}
      - YTDL_OPTS_MERGE_FORMAT=${YTDL_OPTS_MERGE_FORMAT}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_BASE_PATH=${DROPBOX_BASE_PATH}
    image: worker
    hostname: worker
    container_name: worker
    restart: always
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./tmp:${TEMP_DIR}
